[package]
name = "avalanche-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.2", features = ["headers"] }
base64 = "0.21.0"
bcrypt = "0.14.0"
ansi-to-html = "0.1.2"
eyre = "0.6.8"
bytes = "1.4.0"
url = { version = "2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
erased-serde = "0.3.24"
color-eyre = "0.6"
fluent = "0.16.0"
futures = "0.3.26"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
http = "0.2.8"
serde_json = "1.0.91"
governor = "0.5.1"
tracing = "0.1"
mime_guess = "2.0.4"
mime = "0.3.16"
rust-embed = { version = "6.4.2"}
regex = "1.7.1"
tower = "0.4"
humantime = "2.1.0"
http-body = "0.4"
tower-http = { version = "0.3", features = ["trace", "auth"] }
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.11" }
deadpool-sqlite = "0.5.0"
libsqlite3-sys = { version = "0.25", features = ["bundled"] }
sea-query = { version = "0.28", features = ["thread-safe", "backend-sqlite", "derive", "attr"]}
sea-query-rusqlite = { version = "0.2", features = ["with-json", "with-time", "with-uuid"]}
axum-reporting = { git = "https://github.com/kellpossible/axum-reporting.git" }
toml = "0.7.2"
i18n-embed = { version = "0.13.8", features = ["fluent-system"] }
i18n-embed-fl = "0.6.5"
once_cell = "1.17.0"
unic-langid = { version = "0.9.1", features = ["serde"] }
time = { version = "0.3.17", features = ["serde", "parsing", "formatting", "macros"] }
resvg = { version = "0.29.0", default-features = false, features = ["filter", "text", "memmap-fonts"] } # required only for svg to png diagram generation
reqwest = { version = "0.11.14", default-features = false, features = ["json", "stream", "rustls-tls"] }
secrecy = { version = "0.8.0", features = ["serde"] }
usvg-text-layout = { version = "0.29.0", default-features = false, features = ["memmap-fonts"]}
buildstructor = "0.5"
minijinja = { version = "0.30.2", features = ["source", "builtins", "urlencode", "json"] }
minijinja-autoreload = { version = "0.30.2" }
async-trait = "0.1.64"
refinery = { version = "0.8", features = ["rusqlite"] }
uuid = { version = "1.3.0", features = ["v4"] }

[dev-dependencies]
insta = { version = "1.26.0", features = ["json"]}

[build-dependencies]
fs_extra = "1.2.0"

[workspace]
members = ["admin-password-hash"]
