[package]
name = "avalanche-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
forecast-spreadsheet = { path = "./forecast-spreadsheet" }
geo = { path = "./geo" }

axum = { version = "0.6.20", features = ["headers"] }
axum-extra = { version = "0.7.7", default-features = false, features = ["cookie"] }
base64 = "0.21.0"
bcrypt = "0.15.0"
ansi-to-html = "0.1.2"
eyre = { workspace = true }
bytes = "1.4.0"
url = { version = "2.3", features = ["serde"] }
serde = { workspace = true, features = ["derive"] }
erased-serde = "0.3.24"
serde_urlencoded = "0.7.1"
color-eyre = "0.6"
fluent = "0.16.0"
futures = "0.3.26"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
http = "0.2.8"
serde_json = { workspace = true }
governor = "0.6.0"
tracing = "0.1"
mime_guess = "2.0.4"
mime = "0.3.16"
rust-embed = { version = "8.0.0", features = ["include-exclude"] }
regex = "1.7.1"
tower = "0.4"
humantime = "2.1.0"
nonzero_ext = "0.3.0"
http-body = "0.4"
time-tz = { workspace = true }
tower-http = { version = "0.4", features = ["trace", "auth"] }
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
tokio-stream = { version = "0.1.11" }
deadpool-sqlite = { git = "https://github.com/bikeshedder/deadpool.git" } # Needed for new version of rusqlite
thiserror = "1.0.38"
libsqlite3-sys = { version = "0.26", features = ["bundled"] }
sea-query = { version = "0.30", features = ["thread-safe", "backend-sqlite", "derive", "attr"]}
sea-query-rusqlite = { version = "0.4", features = ["with-json", "with-uuid"]}
rusqlite = { version = "0.29.0", features = ["blob"]}
axum-reporting = { git = "https://github.com/kellpossible/axum-reporting.git" }
# axum-reporting = { path = "../axum-reporting" }
toml = "0.8.0"
i18n-embed = { version = "0.14.0", features = ["fluent-system"] }
i18n-embed-fl = "0.7.0"
once_cell = { workspace = true }
unic-langid = { workspace = true, features = ["serde"] }
time = { workspace = true, features = ["serde", "parsing", "formatting", "macros"] }
resvg = { version = "0.29.0", default-features = false, features = ["filter", "text", "memmap-fonts"] } # required only for svg to png diagram generation
reqwest = { version = "0.11.14", default-features = false, features = ["json", "stream", "rustls-tls"] }
secrecy = { version = "0.8.0", features = ["serde"] }
usvg-text-layout = { version = "0.29.0", default-features = false, features = ["memmap-fonts"]}
buildstructor = "0.5.4"
minijinja = { version = "1.0.7", features = ["loader", "builtins", "urlencode", "json"] }
urlencoding = "2.1.2"
minijinja-autoreload = { version = "1.0.7" }
async-trait = "0.1.64"
uuid = { version = "1.3.0", features = ["v4"] }
sha2 = "0.10.6"
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
insta = { version = "1.26.0", features = ["json"]}

[build-dependencies]
fs_extra = "1.2.0"

[workspace]
members = [
    "admin-password-hash",
    "forecast-spreadsheet",
    "geo",
    "geo/debug",
]

[workspace.dependencies]
time = "0.3.17"
time-tz = "2.0.0"
serde = "1.0.188"
serde_json = "1.0.106"
indexmap = "1.9.3"
eyre = "0.6.8"
once_cell = "1.18.0"
unic-langid = "0.9.1"
