[package]
name = "avalanche-report"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.2", features = ["headers"] }
eyre = "0.6.8"
url = { version = "2.3", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
color-eyre = "0.6"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
html-builder = "0.4.0"
serde_json = "1.0.91"
tracing = "0.1"
mime_guess = "2.0.4"
rust-embed = { version = "6.4.2"}
regex = "1.7.1"
tokio = { version = "1.24.1", features = ["macros", "rt-multi-thread"] }
deadpool-sqlite = "0.5.0"
libsqlite3-sys = { version = "0.25", features = ["bundled"] }
sea-query = { version = "0.28", features = ["thread-safe", "backend-sqlite"]}
axum-reporting = { git = "https://github.com/kellpossible/axum-reporting.git" }
ron = "0.8"
i18n-embed = { version = "0.13.8", features = ["fluent-system"] }
i18n-embed-fl = "0.6.5"
once_cell = "1.17.0"
unic-langid = "0.9.1"
resvg = { version = "0.28.0", default-features = false, features = ["filter", "text", "memmap-fonts"] } # required only for svg to png diagram generation
usvg-text-layout = { version = "0.28.0", default-features = false, features = ["memmap-fonts"]}
buildstructor = "0.5"
tinytemplate = "1.2.1"
# refinery = { version = "0.8", features = ["rusqlite"]}

[dev-dependencies]
insta = { version = "1.26.0", features = ["json"]}

[build-dependencies]
fs_extra = "1.2.0"
